services:
  - type: web
    name: portfolio-resume
    env: php
    plan: free
    buildCommand: ./render-build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: NODE_VERSION
        value: 20
      - key: PHP_VERSION
        value: 8.3
